#!/bin/sh

prefix="/opt"
PATH=${prefix}/bin:${prefix}/sbin:/sbin:/bin:/usr/sbin:/usr/bin

start() {
	echo "starting quicktun"
	insmod tun
	TUN_MODE=1 \
	REMOTE_ADDRESS=0.0.0.0 \
	REMOTE_PORT=0000 \
	TUN_UP_SCRIPT="ifconfig utun0 inet 10.4.0.1 10.4.0.2 up" \
	PRIVATE_KEY="run quicktun.keypair LOCALLY and paste the SECRET key here" \
	PUBLIC_KEY="run quicktun.keypair REMOTELY and paste the PUBLIC key here" \
	quicktun &
	}

stop() {
	echo "stopping quicktun"
	killall quicktun
	sleep 2
	rmmod tun
        }

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                sleep 4
                start
                ;;
        *)
                echo "Usage: $0 (start|stop|restart)"
                exit 1
                ;;
esac

exit 0
